### PR TITLE
User interface1

### PR DESCRIPTION
**Pull request by raleighgreen**
Hey Kevin,

Thanks for the git pull clarification - that worked out great.

Here's a progress update:
With this latest version, the scales and keys can now be chosen with buttons! Currently, all of the output is via console.log, however I was really happy to get things working (having success hooking up the buttons as well as being able to display the data along with the fretboard output felt like a great learning milestone!). How does the code look at this stage before I try to display to the screen with p5? Any refactoring or different approaches needed at this stage?

Thanks so much and hope you have a great weekend!

### CODE REVIEW

**Comment by kmcgillivray** [comment]
Excellent work getting this to work! This is a big milestone  a perfect example of a working rough draft, it's complete and does exactly what we wanted it to do, and now we can do some refactoring to really polish it up. Very much like completing a rough draft of your first novel and then getting feedback from an editor! The main points of feedback right now are:
1. We need a more concise way to set up the click event handlers, there's a lot of repeated code in there!
2. Updating the note ID property to change what is displayed in the console works but it is a bit concerning because overwriting the ID deletes the original ID value which means we lose the number we're using to keep track of notes. The notes are still in an array so that could work for continuing to track notes, but we generally want to avoid overwriting the core data of our objects in cases like this. A safer solution would be to add a property to each fret object called `active` and set that to `true` or `false` for each fret if it has a note that is in the found scale.
3. This is something we haven't talked about yet, but we can now reorganize the order that things appear in the script. I'll demonstrate the typical order in the other branch that I'll make and we can talk through it in a meeting.

There are other details to talk about related to each of those points, but those are the main notes. I'm going to go ahead and merge this in, and then I'm going to create a new branch with a revised file demonstrating how I would refactor things a bit. Don't merge my branch in, just take a look at it and then see if you can apply the same ideas to your copy of the script to address the points above. I'd rather talk through this refactoring together in a meeting, but in the interest of time and in case you are working over the weekend I'll just send it over as an example you can look at!

**Comment by raleighgreen** [comment]
Awesome, thanks so much Kevin!
Looking forward to digging into your suggestions over the weekend.
Ttys!

rg

**Comment by kmcgillivray** [comment]
@raleighgreen just pushed the branch! Here's a link to it: https://github.com/raleighgreen/fretArt/tree/scale-refactor-example

**Comment by raleighgreen** [comment]
Great, thanks!

rg

**Pull request merged**
