### PR TITLE
Stuck on how to draw shapes

### PR DESCRIPTION
**Pull request by raleighgreen**
Hey Kevin,

I've gone through a ton of approaches with trying to draw the lines.
Unfortunately I don't think I'm going in the right direction. 

I wanted to make the `vertex()` coordinates based on `vertex(this.x, this.y)` so that the vertices could be constrained by the chosen scale. Although I was able to constrain the notes in some ways (like by octave or string), even when I finally figured out how to isolate the notes on a given string down to one or two notes, the lines would draw together themselves connecting to each other rather than sequentially drawing the outline of the shape.

Also, unfortunately, the audio for the video I made of our last meeting ended up getting messed up (the audio settings that I fussed with ended up making it so that I recorded my voice but not yours - sure do wish it had been the other way around, lol!). I had a hard time deciphering the video, even with the code examples there, as a result. I'll go back to my original screen recording preferences next time so that I will have audio and video - it's really helpful.

So I am wondering:
Before pausing fretArt and switching to the AngularJS material?

1) Do you have any thoughts on how to define the shapes with lines, make them appear correctly and also have them work in concert with the current key and scale? I've definitely hit a wall with it. 

2) Is it too ambitious to try and get this line feature working before we switch to Angular next week? For what it's worth, I have all day available to work tomorrow (Friday) and also have available work time this weekend. I'd be psyched to give it a shot, but I think I'd need some help in order to make any definitive progress with it.

3) Slightly unrelated question: how long would it take to show me how to set up a local server (so that I can make use of P5 audio functions)? Is that something that we could do quickly together in the next meeting, or are instructions available online for your preferred method?

Thanks so much!

### CODE REVIEW

**Comment by raleighgreen** [comment]
Hey Kevin, just a quick update with this pull request. I worked on this all day. I've tried everything I could possibly think of and have added a few new commits that explore other way to get the lines to display dynamically. But after giving it my all, I am totally stumped as to how to get this to work. The most recent commit (b2d78ce) include some comments that outline what I was trying to do and where I got stuck. Any ideas on how I can get past this rut?

**Comment by raleighgreen** [comment]
Hey Kevin,

Well, I think I've officially hit a wall with getting control of the lines (I can draw them fine, but I can't figure out how to generate them dynamically based on the current key/scale).

I wish that this was one of those times where I kept one working and finally got it. Unfortunately, I was not able to do that this time. It was a bit demoralizing as I had gained some confidence after working through the last problems, but I think there were just too many moving parts with this one, and and I'm still just not quite practiced enough to know how to put all of this together. 

This being the case, if we are switching to AngularJS tomorrow, then how should we handle checkpoint 4 and 5 for the capstone project? 

Should I go ahead and submit those last 2 checkpoints in order to list the project as complete on the Bloc Dashboard, and (related question) - given that I wasn't able to get this last feature working, has the work on my end even warranted a pass for those checkpoints?

I haven't heard from you regarding my last pull requests and just wanted to make sure that we are still on track. 

Thanks!

**Comment by kmcgillivray** [comment]
Hey @raleighgreen, thanks for these notes, sorry for my delay getting feedback to you on it. We still have plenty of time for Angular, so let's get this cleaned up tomorrow before we move on to that project. I'll review and make some feedback notes and we'll untangle it together!

**Comment by raleighgreen** [comment]
Sounds great Kevin, ttys!

rg

**Pull request closed without merging**
