### PR TITLE
Fret shapes

### PR DESCRIPTION
**Pull request by raleighgreen**
Hi Kevin,

Hope you had a good weekend!
Just wanted to submit what I have and give you an update.

Here is the most recent version: A C Pedal Tone button has been added, a new scale (melodicMinor) has been added and made default, and the notes now trigger on mouseOver. 

The other thing that I was trying to do today (that I was not able to figure out) is how to make the lines update along with the scale. The button behavior is not yet fully working as expected in relation to the lines. It's probably something simple that I'm missing.

Is that something that we might be able to look at tomorrow?
Thanks very much and ttys!

### CODE REVIEW

**Comment by raleighgreen** [comment]
Hey Kevin,

Just wanted to give you an update, and I also had 2 problems that I was hoping to get your input on.

I was able to map the current scale to the keyboard! Very cool (check the most recent commit ccc082b). The keyboard keys can now play tones and the keyboard mapping is set dynamically by the key and mode! Excellent! However, there are two things that are not yet working that I was hoping to get your input on:

- **Question one**: It won't work to play the same note rapidly - I can only play any given note again once the sound file has finished playing. Do you have any ideas on how I can trigger the same audio file multiple times so that the playback overlaps? Ideally, I'd love to be able to trigger the notes rapid-fire. And this goes for triggering notes on mouseover and on click as well. 

Researching online, I've run across some interesting and informative articles on the Web Audio API like this one: http://teropa.info/blog/2016/08/19/what-is-the-web-audio-api.html. And this one is particularly awesome: http://teropa.info/blog/2016/07/28/javascript-systems-music.html. It seems like using the Web Audio API would work great, but I'm also wondering if it's overkill (plus, I'd need to set up a server to be able to use it). 

If I wanted to make this work without the Web Audio API, could I just clone the given audio file multiple times and then trigger a new instance of it each time the key is pressed in order to simulate the rapid-fire note overlapping effect? Would the Web Audio API have better performance (lower latency in particular) than other non-Web Audio API solutions anyway? What would you recommend?

- **Question two**: Triggering the notes to light up on mouseover and when clicked works great. However, I can't get the notes to light up when the notes are played with the keyboard. Also, when the scale is not-active, the notes won't light up on mouseover like they do when it is active (however, the notes do light up when clicked, regardless of whether or not the scale is active). How can I make the notes light up when triggered with the keyboard, and on mouseover (when the scale is turned off)? Any ideas?

I've hit a wall with the audio triggering issue, so of the two questions I'd say that is the one I need the most help with. I'm going to try and keep working with the button lighting thing since I have been making slow progress with it (I have been able to successfully trigger a note to light up with the keyboard, but it's hardcoded - can't figure out how to make 'this' note light up). 

Thanks so much Kevin - I'd really value any thoughts you have on these 2 issues! 

Side note - I added a simple pedal tone player on the lower right of the screen. It sets the tone to play (and display) based on the current key. So happy to be able to add even simple features on my own! 

Thanks again and have a great weekend!

**Comment by kmcgillivray** [comment]
Hey Raleigh, very happy to see you're feeling confident adding new features on your own! That's a sign of gained experience and a well-organized codebase.

For playing the same note rapid fire, if you're playing the audio files through P5, P5 is likely already using the Web Audio API since that's the standard way to interact with audio files through JavaScript. Therefore, P5 should already have methods built in for stopping/pausing/playing audio. Is there a way when the keypress for each fret is triggered that P5 could first stop the currently playing audio file for that fret if there is one and then play it again?

For triggering the lighting up frets from the keyboard, if I remember correctly, the frets change to their active color when their `playing` property is set to `true`, correct? Can you add logic to the keypress event to change the fret's `playing` property to true so that P5 then draws it in the appropriate color?

Or better yet, can you write a general `play` function that handles all of this logic no matter where the play is triggered from, whether a click, mouseover, or keypress?

**Comment by raleighgreen** [comment]
Quick update: I now have the keyboard mapped correctly based on key, octave, and mode - they now light up as expected! Awesome.
Going to work on audio triggering next. Ttys,

**Comment by raleighgreen** [comment]
Hey Kevin!

Just got your note about being able to freeze for the next two weeks.
Thanks so much for your flexibility with that! I think it will be a better use of the time to hold off on and then restart when I have work time available again in two weeks.

Also, thanks so much for your flexibility with the project - I really do appreciate it. I know we had talked about moving on to other projects, but the way that this app is shaping up, I am now very excited to see it through. Regardless, I'll be sure to give it lots of consideration and then, as you suggested, we can discuss after the break.

In the meantime, I was finally able to get the `playing` notes to fade out using `lerp()`!
Still trying to figure a few quirky things with the light fade, but making progress.

Thanks again for everything Kevin,
Talk to you soon and hope you have a great holiday!

**Comment by raleighgreen** [comment]
Hey Kevin,

Thanks so much for the meeting today - so sorry that the audio was so choppy!
As you said, hopefully it will have fixed itself by next time.

So, I was able to do some work tonight after teaching and I was happy to have figured out how to make the pedal tone re-light with each re-play of the note (yay!). The only unexpected behavior I'm noticing is that the light fades out faster than expected once the note starts repeating (the first note lights and fades as expected, it's the notes that follow that fade too fast). I'm torn as to whether or not to spend time trying to figure this one out. It's currently close enough to expected behavior that I'm totally fine leaving it as is, but the fact that it's different at all is really puzzling.

Speaking of puzzling, one of the notes triggered by the keyboard keys has a small amount of latency present that the others don't. This is the next thing that I'd like to try and figure out how to fix, but I'm not even sure how to begin to troubleshoot it!

Here is a more detailed description of what is happening:

When the fretShapes page first loads, C Ionian is the default key and mode. Trigger a high 'F' note with the '2' key or the 'o' key (they trigger the same note) and the 'F' on the 13th fret High E string, 18th fret B string, and 22nd fret G string will play. Listen closely to the timing.
 
Now play any other note and listen to the timing. There is a small amount of latency present with the triggering of that high F that is not there with the other notes.

One way to observe this more directly is to play two notes at once. For example, if you type the 'i' and the 'p' keys simultaneously, then you will hear an 'E' and a 'G' play simultaneously. However, if you type the 'o' and the '[' keys simultaneously, they will not play simultaneously - the 'o' key will sound slightly later than '['. 

It's worth mentioning that those three frets are the only ones affected. If I switch to another key that doesn't have an 'F' in it, then none of the notes in the scale will exhibit any latency. Furthermore, if you switch to another key or scale, as long as it has that problematic 'F' note in it, then that those three high 'F's will sound later than the others.

It seems so random that only that pitch (those frets) would be affected. Any ideas on why this is happening and how to fix it?

Any input would be great appreciated - totally stumped!

--------------------------------------

Separately, just as a general outline, here are the rest of the issues that I feel need addressed before fretShapes is ready to release:

**1)** When a new key or scale is chosen, make current key and scale update regardless of whether or not the scale is visible. Currently, key and mode only update when show scale is turned on.

**2)** Make it work with 5, 6 and 8 note scales (option for chromatic 12 note would be nice as well).

**3)** Make it so that notes can be triggered on mouseover even if the note is currently playing.

**4)** Make it so that notes only trigger one time even if keyboard keys are held down.

**5)** Make it possible to trigger diatonic scale tones on mouseover even when scales are turned off.

**6)** Make it work with slanted diagonal left and diagonal right line connections as well as just vertical (as it is now).

Regarding the todos above, **1)**, **2)** and **3)** are pretty necessary. **4)** and **5)** are not really crucial, but would be nice to address. For **6)**, I'd love to get this working, but only if it's a fairly manageable feature to add. 

I think I will try to look into **1)** tomorrow - will let you know how it goes!
In the meantime, do you have any thoughts on the 'F' note latency mystery?

Thanks so much Kevin!
ttys

**Comment by raleighgreen** [comment]
Hey Kevin,

Hope you had a good weekend!
Our meeting time switch looks like it's all set for Fridays at 11:30.
Also thanks again for offering to meet with me today at 11:30 - really appreciated!

So for the sake of efficiency, here are the two main things I was thinking we could tackle today:

1) When a note is triggered by mouseover and then re-triggered by mouseover as the note is still playing, note will light up as intended, but the note's audio won't trigger until the initially triggered clip is done playing. Instead, behavior should be: The note should light up and sound once per mouseover regardless of whether or not the note is playing or not. Seems to be a bit of a catch 22. This code in Fret.js below is a necessary safeguard from over triggering, but it also keeps the note from re-triggering at all. How to make it possible to re-trigger the note so that it plays once per re-trigger?

          if (!audioNote.isPlaying()) {
             audioNote.play();
          }

2)  How to fix F note latency issue?

And if we have time, I had these general questions that I was hoping to get your input on:
- What do I need to do to to make fretShapes work on my web server? I tried placing the files in a folder and it didn't quite work. Check http://raleighgreen.com/fretShapes/ for example.
- I'm trying to think of what is the best way to present the app. A web app or an actual app? [Here](https://www.youtube.com/watch?v=kvsDCBrP7b8&t=3s) is a tutorial that will take a hype file and wrap it in Swift in Xcode in order to make a build-able app that can be sold on the apple app store. If a Hype file can be converted to an app, is there any reason that my fretShapes project couldn't be turned into an app since it's made up of the same ingredients?
- What are the differences of potential downsides of building/releasing an app this way?
- Should I be concerned about all the errors I get from P5 in the console?

Thanks Kevin, ttys!

**Comment by raleighgreen** [comment]
Hey Kevin,

Thanks again for the meeting this morning.
Quick follow up - I went ahead and moved the color changes into a separate function and refreshed the browser with a new window. The responsiveness is now totally excellent and it is now acting exactly how it should. Nice to check that todo off as done. Thanks again for the help with that!

**Pull request closed without merging**
